name: Trigger Webhook After Docker Build

on:
  workflow_run:
    workflows: ["Build & Push to GHCR"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send POST to Webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "bot_name": "${{ github.repository }}",
              "secret": "${{ secrets.WEBHOOK_SECRET }}",
              "token": "90091783785371040:0:wCEAyu51h2Qj2HY6DfSwaGZrMUiUvE"
            }'

